services:
  - type: web
    name: mygpt-backend-node
    env: node
    plan: free
    branch: main
    rootDir: backend-node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
