openapi: 3.1.0
info:
  title: MyGPT Notes API
  version: "1.0.0"

servers:
  - url: https://mygpt-backend-node.onrender.com

paths:
  /status:
    get:
      operationId: getStatus
      summary: Check API status
      responses:
        "200":
          description: API status OK
          content:
            application/json:
              example:
                status: OK
                backend: Node
                version: 1.0.0

  /notes:
    get:
      operationId: getNotes
      summary: Get all notes
      responses:
        "200":
          description: List of notes
          content:
            application/json:
              example:
                - id: 1
                  title: First Note
                  content: Example note
                  createdAt: "2025-08-04T20:00:00Z"

components:
  schemas: {}
